### ISSUE TITLE
Fetch all activities?

### ISSUE THREAD

**Issue by bagage** [yizeng/strava-best-efforts#12]
When you modify the sport type of an activity, all badges/best efforts are not computed again. This can be an issue when an activity is your best effort for all distances and you do not modify its sport immediately. 
All following activities will be "2nd best effort" at most and they will be left as is even if you modify sport of the first one. You end up with no "1st best effort" activity, and strava-best-efforts won't display any then.

One solution would be to recompute all activities achievements using `/activities/:id/refresh_achievements` but this API is not available. 
The other solution would be to modify strava-best-efforts to fetch all activities instead using `/activities/:id` and use `best_efforts` array which holds, for a given activity, all the records for this activity. However that requires some extra processing on client side to find best activities.

edit: actually this is already done like that. But strava-best-efforts looks for `pr_rank` in `best_efforts`, which is imo terribly broken (at least for users who modify sport type after having uploaded to strava). Might it make sense to sort the list instead of using it?

**Comment by yizeng** [comment]
Hey hey, thanks for writing! @bagage 

Yes, I noticed about that before I started doing this app.

I think it's how Strava best efforts are designed. When you recompute all activities achievements on Strava, it doesn't recalculate everything based on a timely order. It just recalculates that one particular activity. 

Say for example,
Activity ID 11111: 5k 20 minutes, 1st best efforts for 5k
Activity ID 22222: 5k 25 minutes, 2nd best efforts for 5k
Activity ID 33333: 5k 21 minutes, 2nd best efforts for 5k
Activity ID 44444: 5k 23 minutes, 3rd best efforts for 5k

Then you change the activity of 11111, so there will be no more '1st best efforts' for 5k and everything else remain unchanged (i.e. there are two '2nd best efforts' for 5k). If you refresh the achievements of 22222 now, it will be '3rd best efforts for 5k'. Because Strava calculates achievements based on all existing activities as of the time you refresh , 25 minutes is the '3rd best efforts for 5k' at the time when you refresh. So you would never get  '1st best efforts' back. It's probably too much work for Strava to provide something to recalculate everything in time order.

Why not use `best_efforts` but `pr_rank`? Because when I designed this, I just wanted to have the best efforts exactly the same as shown in Strava, so what I see in this app would be the consistent cross Strava UI. If there is no '1st best effort' on Strava, I shouldn't see it here either.

Does that make sense?

**Comment by bagage** [comment]
Yeah it makes sense, even though it's not what I am looking for - do you think it would made sense to add a value for parameter "pr_rank" such as "0", or "none": in that case, `strava-best-efforts` would download all activities? It's basically what [I have done](https://github.com/bagage/strava-best-efforts/commit/9fc67c8e409eb4bfa239f16d026406f4fc8a2df7).

**Comment by yizeng** [comment]
Yes, we can download all activities. But as I explained above (last paragraph), would that make best efforts data in this app inconsistent with Strava best efforts data (i.e. those badges/trophies), because those are `pr_rank`?

**Comment by bagage** [comment]
Yes they would be inconsistent - but since strava best efforts are unreliable, I prefer just to see all activities. But again that's really personal: for me `strava best efforts` means *the actual activities where I performed the best*, not *actvities Strava thinks I've done the best*.

Their is no effect in the rate limits, since the application downloads all activities in any case to see if it contains a best effort. Their is no extra cost thus.

**Comment by yizeng** [comment]
Agreed, it's more about personal preference.

Initially I want this `strava-best-efforts` to visualize Strava best efforts, not create an algorithm to calculate best efforts and ignore what's on Strava. It means when I click an activity in the data table, I want to see a gold badge there on Strava. If this app calculates the best efforts ourselves, some people might wonder, how come I don't see the gold trophies on Strava?

"Strava Estimated Best Efforts" is a term created and defined by Strava, which is a quite odd but truely unique name, so the app should follow what's on Strava in order to be consistent. "actual activities where I performed the best" is something can be defined by any individuals, sometimes commonly know as "PBs". The algorithm can be defined differently by different people, but it won't be related to the term "Strava best efforts".

**Comment by bagage** [comment]
Yeah, it makes sense - I guess we have to different objectives with it, so I'm fine with this being closed. I'll use my own fork which is fine. Thanks for your explanations!
