### ISSUE TITLE
Weird looking graphs

### ISSUE THREAD

**Issue by bagage** [yizeng/strava-best-efforts#13]
Graphs are looking odd:

![capture d ecran de 2016-12-26 15-07-47](https://cloud.githubusercontent.com/assets/1451988/21482469/b754ac2e-cb74-11e6-9df9-b01db0f5b058.png)

This is because strava-best-results sorts activities by id instead of start_date. In my case, some bigger activity ids are older than previous ones.

**Comment by yizeng** [comment]
Thanks for reporting! @bagage 

Yeah, as I don't have enough data to test, surely there are lots of bugs like this one.

I'm actually rewriting this app using Ruby on Rails, if you have time, please have a play around at http://strafforts.yizeng.me. Thanks! I believe this issue also happens there, because the JS code is the same.

The new app is only just work in progress at the moment, so it's not open sourced yet and server won't be up all time in order to minimize the costs.
